### ISSUE TITLE
Pet Management

### ISSUE THREAD

**Issue by samymsa** [MonChenil/monchenil#10]
As a pet owner, I want to add details of my pets to the system so that I can book kennel slots for their stay.

Acceptance Criteria:

- [x] Clients logged in can add details of their pets (name, type, etc.).
- [ ] Clients can specify if their pet(s) are not compatible with certain pet types (e.g., "My pet is not compatible with cats").

**Comment by samymsa** [comment]
Back is done, need to do front

**Comment by ybokhari** [comment]
For 10998c75158c07fc6427b7660c44042913a10bc5

Bugs to fix :
- Min length validation for animal name is not working
- Convert data to an appropriate type (don't use any) when sending to PetsService

To do :
- Connect the back-end to the front
